name: Release to Gradle Plugin Portal
on: [workflow_dispatch]

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8
            - name: Set version to release version
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: prepareReleaseVersion
            - name: Get version to release
              id: version
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: saveVersionForGitHub
            - name: Commit changes
              uses: EndBug/add-and-commit@v4
              with:
                  add: build.gradle.kts
                  tag: v${{steps.version.outputs.version}}
                  message: Prepare release for ${{steps.version.outputs.version}}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: Set Gradle Publish Credentials
              uses: eskatos/gradle-command-action@v1
              env:
                GRADLE_API_KEY: ${{ secrets.GRADLE_API_KEY }}
                GRADLE_API_SECRET: ${{ secrets.GRADLE_API_SECRET }}
              with:
                arguments: setupPluginUploadFromEnvironment
            - name: Release
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: publishPlugins
            - name: Set version to next SNAPSHOT version
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: prepareNextSnapshotVersion
            - name: Get version to release
              id: nextversion
              uses: eskatos/gradle-command-action@v1
              with:
                  arguments: saveVersionForGitHub
            - name: Commit changes
              uses: EndBug/add-and-commit@v4
              with:
                  add: build.gradle.kts
                  message: Prepare for next development iteration with version ${{steps.nextversion.outputs.version}}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
